{
	"version": 1705548531,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/tiledbackground2.png",
		"images/tilemap2.png",
		"images/sprite-sheet0.png",
		"images/player-sheet0.png",
		"images/player-sheet1.png",
		"images/player-sheet2.png",
		"images/particlesrun.png",
		"images/tiledbackground3.png",
		"images/sprite3-sheet0.png",
		"images/play-sheet0.png",
		"images/setting-sheet0.png",
		"images/quit-sheet0.png",
		"images/psetting-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/close-sheet0.png",
		"images/musik-sheet0.png",
		"images/camera-sheet0.png",
		"images/spike.png",
		"images/horizontal-sheet0.png",
		"images/manuk-sheet0.png",
		"images/manuk-sheet1.png",
		"images/pembatasenemy-sheet0.png",
		"images/pitik-sheet0.png",
		"images/pitik-sheet1.png",
		"images/saw-sheet0.png",
		"images/kiwi-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/efekdestroy-sheet0.png",
		"images/efekdestroy-sheet1.png",
		"images/apel-sheet0.png",
		"images/pisang-sheet0.png",
		"images/finish-sheet0.png",
		"images/finish-sheet1.png",
		"images/musikoff-sheet0.png",
		"images/restart-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/cursor-sheet0.png",
		"images/trampolin-sheet0.png",
		"images/trampolin-sheet1.png",
		"media/y2mate.com - jump sound effect.ogg",
		"media/dash_1.ogg",
		"media/1pop.ogg.ogg",
		"media/y2mate.com-geometry-dash-death-sound-effect.ogg",
		"media/y2mate.com-video-game-start-sound-effect.ogg",
		"media/y2mate.com - footstep walk game sound royaltyfree.ogg",
		"media/whatsapp audio 2023-12-01 at 09.21.32_99a5ae7d.ogg",
		"media/y2mate.com-like-a-dino-its-ok-to-not-be-ok-12x-speed.ogg",
		"media/y2mate.com-sound-effect-lompat-super-mario.ogg",
		"media/pop.ogg",
		"media/lompat.ogg",
		"media/dash.ogg",
		"media/y2mate.com - 8bit video game pop free sound effect 4.ogg",
		"media/intro-theme.ogg",
		"media/y2mate.com - earthbound  smiles and tears hq.ogg",
		"generator_config.txt",
		"press2p.css",
		"pressstart2p-demo.html",
		"pressstart2p-webfont.eot",
		"pressstart2p-webfont.svg",
		"pressstart2p-webfont.ttf",
		"pressstart2p-webfont.woff"
	]
}